run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive

linters-settings:
  goimports:
    local-prefixes: github.com/eddyjj92/goravel-inertia

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
